[package]

# Semantic Versioning is used: https://semver.org/
version = "1.0.0"

# Description
title =  "robotis_lab Tasks"
description=""
readme  = "README.md"
repository = "https://github.com/ROBOTIS-GIT/robotis_lab.git"
category = "robotics"
keywords = ["extension", "robotis_lab", "isaaclab"]

[dependencies]
"isaaclab" = {}

[core]
reloadable = false

# Main python module this extension provides.
[[python.module]]
name = "robotis_lab"
